export { default as Banner } from './Banner';
export { default as Catagories } from './Catagories';
export { default as NavBar } from './Navbar';
export { default as NewsCard } from './NewsCard';
export { default as TopPosts } from './TopPosts';
export { default as News } from './News';
export { default as Container } from './Container';
export { default as Footer } from './Footer';
export { default as SearchBar } from './SearchBar';
